config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [ :registrations ]
  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :courses do
    resources :lessons
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :checkouts, only: [:create]

  namespace :admin do
    resources :courses do
      resources :lessons
    end
    resources :users
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*


  # Defines the root path route ("/")

  get "admin" => "admin#index"

  post "/webhook" => "webhooks#stripe"
  patch "admin/courses/:course_id/lessons/:id/move" => "admin/lessons#move"
  root "courses#index"
end

app/views/admin/_navbar.html.erb
<header class="hidden sm:flex w-full justify-center items-center text-gray-700 py-6 px-5">
  <div class="container mx-auto flex justify-between items-center">
    <div class="flex">
      <div>
        <%= link_to "Dashboard", admin_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      </div>
      <div>
        <%= link_to "Courses", admin_courses_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      </div>
      <div>
        <%= link_to "Users", admin_users_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      </div>
    </div>
    <div>
      <%= link_to admin_path do %>
        <% image_tag "hehe.jpg", class: "h-12" %> 
      <% end %>
    </div>
    <div class="flex">
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { 'turbo_method' => :delete, 'turbo_confirm' => "Are you sure?" }, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
      <% end %>
    </div>
  </div>
</header>

<header data-controller="navbar" class="bg-amaranth-500 sm:hidden w-full py-4 px-5 text-white-50">
  <div class="flex justify-between items-center">
    <div>
      <%= link_to admin_path do %>
        <%= image_tag "hehe.jpg", class: "h-12" %>
      <% end %>
    </div>
    <div class="p-4">
      <button data-action="click->navbar#toggle" id="bars" type="button" class="w-full flex justify-end items-center">
        <%= icon('fa-solid', 'bars') %>
      </button>
      <button data-action="click->navbar#toggle" id="close" type="button" class="hidden w-full flex justify-end items-center">
        <%= icon('fa-solid', 'x') %>
      </button>
    </div>
  </div>

  <div id="mobile-links" class="hidden border-t-2 border-amaranth-400 flex flex-col w-full justify-center items-center">
    <div class="mt-4">
      <%= link_to "Dashboard", admin_path, class: "hover:bg-amaranth-700 rounded py-2 px-4" %>
    </div>
    <div class="mt-4">
      <%= link_to "Courses", admin_courses_path, class: "hover:bg-amaranth-700 rounded py-2 px-4" %>
    </div>
    <div class="mt-4">
      <%= link_to "User", admin_users_path, class: "hover:bg-amaranth-700 rounded py-2 px-4" %>
    </div>

    <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, data: { 'turbo_method' => :delete, 'turbo_confirm' => "Are you sure?" }, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "hover:bg-amaranth-500 hover:text-white-50 rounded py-2 px-4" %>
    <% end %>
  </div>
</header>

app/views/admin/index.html.erb
<div class="w-full flex flex-col justify-start items-center">
  <h1 class="font-bold text-4xl mb-4 md:mb-10 text-start w-full">Admin Dashboard</h1>
  <div class="flex flex-col gap-10 justify-center md:flex-row items-center md:justify-between w-full">
    <div class="max-w-sm rounded overflow-hidden w-full md:w-48 shadow-xl bg-gradient-to-r from-amaranth-400 to-amaranth-300">
      <div class="px-6 py-4">
        <h2 class="font-bold text-xl mb-2 text-amaranth-50">Sign Ups</h2>
        <p class="text-amaranth-50 text-base">
          <%= @quick_stats[:sign_ups] %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden w-full md:w-48 shadow-xl bg-gradient-to-r from-amaranth-400 to-amaranth-300">
      <div class="px-6 py-4">
        <h2 class="font-bold text-xl mb-2 text-amaranth-50">Sales</h2>
        <p class="text-amaranth-50 text-base">
          <%= @quick_stats[:sales] %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden w-full md:w-48 shadow-xl bg-gradient-to-r from-amaranth-400 to-amaranth-300">
      <div class="px-6 py-4">
        <h2 class="font-bold text-xl mb-2 text-amaranth-50">Lessons Done</h2>
        <p class="text-amaranth-50 text-base">
          <%= @quick_stats[:completed_lessons] %>
        </p>
      </div>
    </div>
    <div class="max-w-sm rounded overflow-hidden w-full md:w-48 shadow-xl bg-gradient-to-r from-amaranth-400 to-amaranth-300">
      <div class="px-6 py-4">
        <h2 class="font-bold text-xl mb-2 text-amaranth-50">Total Sign Ups</h2>
        <p class="text-amaranth-50 text-base">
          <%= @quick_stats[:total_sign_ups] %>
        </p>
      </div>
    </div>
  </div>

  <div class="w-full flex flex-col justify-between items-center md:flex-row mt-8" data-controller="dashboard" data-dashboard-signups-value=<%= @sign_ups_by_day.to_json %> data-dashboard-completed-value=<%= @completed_lessons_by_day.to_json %>>
    <div class="w-full md:w-1/2">
      <h2 class="font-bold text-2xl my-8 text-center">Completed Lessons</h2>
      <canvas id="chart"></canvas>
    </div>
    <div class="w-full md:w-1/2">
      <h2 class="font-bold text-2xl my-8 text-center">Sign Ups</h2>
      <canvas id="sign_ups_chart"></canvas>
    </div>
  </div>

  <div class="w-full overflow-x-auto my-6">
    <h2 class="font-bold text-2xl my-8">Most Popular Courses</h2>
    <table class="min-w-full bg-amaranth-50" style="border-collapse: separate; border-spacing: 0;">
      <thead>
        <tr class="text-amaranth-800">
          <th class="px-6 py-3 border-b-2 border-amaranth-200 text-start bg-amaranth-100">Title</th>
          <th class="px-6 py-3 border-b-2 border-amaranth-200 text-start bg-amaranth-100">Users</th>
        </tr>
      </thead>
      <tbody class="text-gray-800">
        <% @most_popular_courses.each do |course| %>
          <tr>
            <td class="px-6 py-4 border-b border-gray-200"><%= course.title %></td>
            <td class="px-6 py-4 border-b border-gray-200"><%= course.course_users.count %></td>
          </tr>
        <% end %> 
      </tbody>
    </table>
  </div>

</div> 