config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [ :registrations ]
  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :courses do
    resources :lessons
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :checkouts, only: [:create]

  namespace :admin do
    resources :courses do
      resources :lessons
    end
    resources :users
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*


  # Defines the root path route ("/")

  get "admin" => "admin#index"

  post "/webhook" => "webhooks#stripe"
  patch "admin/courses/:course_id/lessons/:id/move" => "admin/lessons#move"
  root "courses#index"
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_one_attached :video do |attachable|
    attachable.variant :thumb, resize_to_limit: [500, 500]
  end

  acts_as_list
  has_rich_text :description
  belongs_to :course
  has_many :lesson_users, dependent: :destroy

  def next_lesson
    course.lessons.where("position > ?", position).order(:position).first
  end

  def previous_lesson
    course.lessons.where("position < ?", position).order(:position).last
  end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < AdminController
  before_action :set_course
  before_action :set_lesson, only: [:move, :show, :edit, :destroy, :update]
  def index
    @admin_lessons = @admin_course.lessons.order(:position)
  end
  def new
    @admin_lesson = @admin_course.lessons.new
  end
  def create
    @admin_lesson = @admin_course.lessons.new(lesson_params)
    if @admin_lesson.save
      redirect_to admin_course_lessons_path(@admin_course)
    else
      render :new

    end
  end
  def show
  end
  def edit
  end
  def update
    if @admin_lesson.update(lesson_params)
      redirect_to admin_course_lessons_path(@admin_course)
    else
      render :edit
    end
  end
  def destroy
    @admin_lesson.destroy!
    redirect_to admin_course_lessons_path(@admin_course)
  end
  def move
    position = params[:position].to_i
    if position == 0
      @admin_lesson.move_to_top
    elsif position == @admin_course.lessons.count - 1
      @admin_lesson.move_to_bottom
    else
      @admin_lesson.insert_at(position + 1)
    end

    @admin_lesson.save!

    render json: { message: "success" }
  end
  private

  def lesson_params
    params.require(:lesson).permit(:title, :description, :video, :paid, :position)
  end
  def set_course
    @admin_course = Course.find(params[:course_id])
  end
  def set_lesson
    @admin_lesson = @admin_course.lessons.find(params[:id])
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: %i[ show update  ]
  before_action :set_course
  before_action :check_paid

  # GET /lessons or /lessons.json


  # GET /lessons/1 or /lessons/1.json
  def show
    @completed_lessons = current_user.lesson_users.where(completed: true).pluck(:lesson_id)
    @course = @lesson.course
    @paid_for_course = current_user.course_users.where(course: @course).exists?
    puts "paid for course #{@paid_for_course}"
  end

  # GET /lessons/new


  # GET /lessons/1/edit
  def update
    @lesson_user = LessonUser.find_or_create_by(user: current_user, lesson: @lesson)
    @lesson_user.update!(completed: true)
    next_lesson = @course.lessons.where("position > ?", @lesson.position).order(:position).first
    if next_lesson
      redirect_to course_lesson_path(@course, next_lesson)
    else
      redirect_to course_path(@course), notice: "You've completed the course"
    end
  end

  # POST /lessons or /lessons.json

  # PATCH/PUT /lessons/1 or /lessons/1.json


  # DELETE /lessons/1 or /lessons/1.json


  private
    def set_course
      @course = Course.find(params[:course_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def check_paid
      if @lesson.paid && !current_user.course_users.where(course_id: params[:course_id]).exists?
        if @lesson.previous_lesson
          redirect_to course_lesson_path(@course, @lesson.previous_lesson),
          notice: "You must purchase the full course to access the next lesson"
        else
          redirect_to course_path(@course),
          notice: "You must purchase the full course to access the nẽt lesson"
        end
      end
    end
  # Only allow a list of trusted parameters through.
end

app/helpers/admin/lessons_helper.rb
module Admin::LessonsHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, class: "contents") do |form| %>
  <% if lesson.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :paid %>
    <%= form.check_box :paid, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :course_id %>
    <%= form.text_field :course_id, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/lessons/_lesson.html.erb
<div id="<%= dom_id lesson %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= lesson.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= lesson.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Paid:</strong>
    <%= lesson.paid %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Course:</strong>
    <%= lesson.course_id %>
  </p>

</div>

app/views/lessons/_sidebar.html.erb
<div class="w-full">
    <% course.lessons.order(:position).each do |lesson| %>
        <% if lesson.paid && !paid_for_course %>
            <div class = "border p-6 hover:bg-gray-200">
                <div>
                    <%= icon('fa-solid', 'lock', class: "mr-2 text-gray-200") %>
                    <span class = "font-light">
                        <%= lesson.title %>
                    </span>
                </div>
            </div>
        <%else%>
            <%= link_to course_lesson_path(course, lesson) do %>
                <div class="border p-6 hover:bg-gray-200 <%= @lesson.id == lesson.id ? 'bg-amaranth-200' : '' %>">
                    <div>
                        <%= completed_lessons&.include?(lesson.id)? 
                            icon('fa-solid', 'check-circle', class: "mr-2 text-green-500") :
                             nil
                        %>
                        <span class = "font-light">
                            <%= lesson.title %>
                        </span>
                    </div>
                </div> 
            <%end%>
        <%end%>
    <%end%>
</div>

app/views/lessons/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Show this lesson", @lesson, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lessons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Lessons" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Lessons</h1>
    <%= link_to "New lesson", new_lesson_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="lessons" class="min-w-full">
    <% @lessons.each do |lesson| %>
      <%= render lesson %>
      <p>
        <%= link_to "Show this lesson", lesson, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/lessons/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New lesson</h1>

  <%= render "form", lesson: @lesson %>

  <%= link_to "Back to lessons", lessons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/lessons/show.html.erb
<div class="flex flex-col lg:flex-row-reverse w-full justify-start lg:justify-end pb-6">
  <div>
    <div>
      <% if notice.present? %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
    </div>

    <%= (@lesson.video.present?) ? (video_tag @lesson.video, autoplay: false, controls: true, class: "rounded") : "No video Avaiable" %>

    <div class = "my-2 border p-4 rounded">
      <h1 class = "text-2xl font-semibold">
        <%= @lesson.title %>
      </h1>
      <p class="text-gray-700">
        <%= @lesson.description %>
      </p>
    </div>
    <div class="my-6 lg:mb-0">
      <%= link_to "Mark as complete", course_lesson_path(@course, @lesson),data: { 'turbo-method' => :put }, class: "bg-amaranth-500 rounded hover:bg-amaranth-800 text-white-50 px-4 py-2" %>
    </div>
  </div>
  <div class = "sidebar_container lg:min-w-60 lg:mr-4 lg:overflow-y-scroll">
    <%= render "sidebar", course: @course, completed_lessons: @completed_lessons , paid_for_course: @paid_for_course %>
  </div>
</div>