config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [ :registrations ]
  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :courses do
    resources :lessons
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :checkouts, only: [:create]

  namespace :admin do
    resources :courses do
      resources :lessons
    end
    resources :users
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*


  # Defines the root path route ("/")

  get "admin" => "admin#index"

  post "/webhook" => "webhooks#stripe"
  patch "admin/courses/:course_id/lessons/:id/move" => "admin/lessons#move"
  root "courses#index"
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController
  def index
    @admin_courses = Course.all
  end
  def new
    @admin_course = Course.new
  end

  def show
    @admin_course = Course.find(params[:id])
  end
  def create
    @admin_course = Course.new(course_params)
    if @admin_course.save
      redirect_to admin_courses_path
    else
      render :new
    end
  end

  def edit
    @admin_course = Course.find(params[:id])
  end

  def update
    @admin_course = Course.find(params[:id])

    if @admin_course.update(course_params)
      redirect_to admin_courses_path
    else
      render :edit
    end
  end
  private

  def course_params
    params.require(:course).permit(:title, :description, :premium_description, :paid, :stripe_price_id, :image)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
    @user_started_courses = current_user&.lesson_users&.joins(:lesson)&.pluck(:course_id)&.uniq
    @user_unlocked_courses = current_user&.lesson_users&.joins(:lesson)&.pluck(:course_id)
    if @user_started_courses.present?
      @user_course_progresses = @user_started_courses.map do |course_id|
        course_lessons = Course.find(course_id).lessons.count
        completed_lessons = current_user&.lesson_users&.joins(:lesson)&.where(completed: true, lessons: { course: course_id })&.count
        { course_id: course_id, completed_percentage: (completed_lessons.to_f / course_lessons.to_f * 100).to_i }
      end
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
    @completed_lessons = current_user&.lesson_users&.joins(:lesson)&.where(completed: true,
    lesson: { course: @course })&.pluck(:lesson_id)
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_path, status: :see_other, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.erb
<div id="<%= dom_id course %>" class="max-w-sm rounded-b overflow-hidden shadow-lg hover:bg-voodoo-100">
  <%= link_to course, class: "flex flex-col h-full" do %>
    <% if course.image.present? %>
      <%= image_tag course.image, class: "w-full rounded-t" %>
    <% else %>
      <%= image_tag("https://via.placeholder.com/300") %>
    <% end %>

    <div class="px-6 py-4 flex flex-col justify-between grow">
      <div>
        <div class="flex items-center justify-between font-bold mb-2">
          <%= course.title %>
          <% if user_unlocked_courses&.include? course.id %>
          <span class = "ml-2 text-white-50 text-xs px-2 py-1 rounded bg-green-500">Unlocked</span>
          <%end%>
        </div>

        <p class="text-sm font-extralight">Hoai Nam</p>

        <div>
          <p class="font-md font-light">
            <%= course.paid ? "Premium Course" : "Free"%>
           
          </p>
        </div>
      </div>
      <% if user_started_courses&.include? course.id %>
        <% user_completed_percentage = user_course_progresses.find { |cp| cp[:course_id] == course.id }[:completed_percentage] %>
        <div class="mt-2 h-4 relative rounded-full overflow-hidden">
          <div class = "w-full h-full bg-gray-200 absolute">
            <% if user_completed_percentage == 100 %>
              <div class= "h-full bg-green-500 absolute text-white-50 text-center text-xs" style = "width: 100%">
                Completed
              </div>
            <%else%>
              <div class= "h-full bg-green-500 absolute text-white-50 text-center text-xs" style = "width: <%= user_completed_percentage %>%">
                <%= user_completed_percentage %>%
              </div>
            <%end%>
          </div>
        </div>
      <%end%>
    </div>
  <% end %>
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course, class: "contents") do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_field :description, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/courses/_sidebar.html.erb
<div class = "flex flex-col lg:pl-6">
    <div class = "mt-6 lg:mt-0 flex justify-center items-center w-full">
        <div class = "bg-white rounded-lg shadow-lg overflow-hidden w-full">
            <div class = "bg-amaranth-500 p-4" >
                <h2 class = "text-white-50 text-2xl font-bold">
                    Start Learning
                </h2>
            </div>
            <div class = "p-4" >
                <% if user_signed_in? %>
                    <% if @completed_lessons&.any? %>
                        <% if @completed_lessons.count == @course.lessons.count %>
                            <p class = "text-gray-700 text-base mb-4">
                                You've completed this course!!!
                            </p>
                            <%= link_to "Watch Again", course_lesson_path(@course, @course.first_lesson), class: "bg-revolver-600 hover:bg-revolver-800 text-white-50 font-bold px-4 py-2 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
                        <%else%>
                            <p class = "text-gray-700 text-base mb-4">
                                Continue course and pick up where you left off!!!
                            </p>
                            <%= link_to "Continue course", course_lesson_path(@course, @course.next_lesson(current_user)), class: "bg-revolver-600 hover:bg-revolver-800 text-white-50 font-bold px-4 py-2 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
                        <%end%>
                    <%else%>
                        <p class = "text-gray-700 text-base mb-4">
                            Start the course and Learning all about the world of web dev!!!
                        </p>
                        <%= link_to "Start Course", course_lesson_path(@course, @course.first_lesson), class: "bg-revolver-600 hover:bg-revolver-800 text-white-50 font-bold px-4 py-2 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
                    <%end%>
                    
                <% else %>
                    <p class = "text-gray-700 text-base mb-4">
                        Sign up for free today and explore the world of web dev!!!
                    </p>
                    <%= link_to "Sign Up", new_user_registration_path, class: "bg-revolver-600 hover:bg-revolver-800 text-white-50 font-bold px-4 py-2 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
                <% end %>
            </div>
        </div>
    </div>
            <% if @course.paid %>
                <div class ="mt-6 flex justify-center items-center w-full" >
                    <div class = "bg-white rounded-lg shadow-lg overflow-hidden w-full">
                        <div class = "bg-amaranth-500 p-4">
                            <h2 class = "text-white-50 text-2xl font-bold">
                                Get more content
                            </h2>
                        </div>
                        <div class="p-4">
                            <% if user_signed_in? %>
                                <p class ="text-gray-700 text-base mb-4">
                                    Unlock more content by purchasing the full course
                                </p>
                                <%= form_tag checkouts_path(@course), method: :post, class: "mt-4" do %>
                                    <%= hidden_field_tag :course_id, @course.id %>
                                    <%= hidden_field_tag :stripeEmail, current_user.email %>
                                    <%= button_tag "Unlock Full Course", class: "bg-revolver-600 hover:bg-revolver-700 text-white-50 font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150", data: {turbo: false} %>
                                <% end %>
                            <%else%>
                                <p class ="text-gray-700 text-base mb-4">
                                    Sign up for free today and satrt exploring the endless possibilities!!!
                                </p>
                                <%= link_to "Sign Up", new_user_registration_path, class: "bg-revolver-600 hover:bg-revolver-800 text-white-50 font-bold px-4 py-2 rounded focus:outline-none focus:shadow-outline w-full transition ease-in-out duration-150" %>
                            <%end%>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/courses/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing course</h1>

  <%= render "form", course: @course %>

  <%= link_to "Show this course", @course, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <% content_for :title, "Courses" %>



  <div id="courses" class="min-w-full flex flex-wrap justify-center gap-14 pb-6">
    <%= render @courses, { user_started_courses: @user_started_courses, 
    user_course_progresses: @user_course_progresses, user_unlocked_courses: @user_unlocked_courses} %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New course</h1>

  <%= render "form", course: @course %>

  <%= link_to "Back to courses", courses_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/courses/show.html.erb
<div class="mx-auto w-full flex flex-col lg:flex-row pd-6">
  <div class="mx-auto w-full">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <% if @course.lessons.any? && @course.lessons.first.video.present? %>
      <%= video_tag @course.lessons.first.video, controls: true, class: "w-full rounded mb-6" %>
    <% end %>
    
    <div class="border p-6 rounded">
      <div class="flex justify-start items-center flex-wrap w-full mb-2">
        <% @course.categories.each do |category|  %>
          <div class="bg-amaranth-100 text-amaranth-800 text-sm font-semibold mt-2 mr-2 px-2.5 py-0.5 rounded">
            <%= category.name %>
          </div>
        <% end %>
      </div>
      <%# pluralize(@course.lessons.count) dùng để thêm s hoặc k thêm nếu có ít hơn 1 lesson %>
      <span><%= @course.lessons.count %> <%= "lesson".pluralize(@course.lessons.count) %> </span>

      <h1 class= "text-2xl font-bold"> <%= @course.title %> </h1>
      <p class="text-gray-500 mt-2">
        <%= @course.description %>
      </p>
    </div>
  </div>
    <div>
      <%= render "sidebar" %>
    </div>
</div>