config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, skip: [ :registrations ]
  devise_scope :admin do
    get "/admins/sign_out" => "devise/sessions#destroy"
  end
  devise_for :users
  resources :courses do
    resources :lessons
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  authenticated :admin_user do
    root to: "admin#index", as: :admin_root
  end

  resources :checkouts, only: [:create]

  namespace :admin do
    resources :courses do
      resources :lessons
    end
    resources :users
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*


  # Defines the root path route ("/")

  get "admin" => "admin#index"

  post "/webhook" => "webhooks#stripe"
  patch "admin/courses/:course_id/lessons/:id/move" => "admin/lessons#move"
  root "courses#index"
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < AdminController
  def index
    @admin_courses = Course.all
  end
  def new
    @admin_course = Course.new
  end

  def show
    @admin_course = Course.find(params[:id])
  end
  def create
    @admin_course = Course.new(course_params)
    if @admin_course.save
      redirect_to admin_courses_path
    else
      render :new
    end
  end

  def edit
    @admin_course = Course.find(params[:id])
  end

  def update
    @admin_course = Course.find(params[:id])

    if @admin_course.update(course_params)
      redirect_to admin_courses_path
    else
      render :edit
    end
  end
  private

  def course_params
    params.require(:course).permit(:title, :description, :premium_description, :paid, :stripe_price_id, :image)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = Course.all
    @user_started_courses = current_user&.lesson_users&.joins(:lesson)&.pluck(:course_id)&.uniq
    @user_unlocked_courses = current_user&.lesson_users&.joins(:lesson)&.pluck(:course_id)
    if @user_started_courses.present?
      @user_course_progresses = @user_started_courses.map do |course_id|
        course_lessons = Course.find(course_id).lessons.count
        completed_lessons = current_user&.lesson_users&.joins(:lesson)&.where(completed: true, lessons: { course: course_id })&.count
        { course_id: course_id, completed_percentage: (completed_lessons.to_f / course_lessons.to_f * 100).to_i }
      end
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
    @completed_lessons = current_user&.lesson_users&.joins(:lesson)&.where(completed: true,
    lesson: { course: @course })&.pluck(:lesson_id)
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_path, status: :see_other, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description)
    end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/admin/courses/_course.html.erb
<div id="<%= dom_id course %>" class = "max-w-xs rounded overflow-hidden shadow-lg">
    <% if course.image.present? %>
        <%= image_tag course.image, class: "w-full" %>
    <%else%>
        <%= image_tag("https://via.placeholder.com/300") %>
    <%end%>
    <div class= "px-4 py-4">
        <div class="font-bold text-xl mb-6">
            <%= course.title %>
        </div>
        <%= link_to "Edit Course", edit_admin_course_path(course), class: "bg-amaranth-500 hover:bg-amaranth-700 text-white-50 font-bold py-2 px-4 rounded" %>
        <%= link_to "View Lessons", admin_course_lessons_path(course), class: "bg-camelot-500 hover:bg-camelot-700 text-white-50 font-bold py-2 px-4 rounded" %>
    </div>
</div>

app/views/admin/courses/_form.html.erb
<%= form_with(model: [:admin, admin_course]) do |form| %>
  <% if admin_course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin_course.errors.count, "error") %> prohibited this admin_course from being saved:</h2>

      <ul>
        <% admin_course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="flex flex-col">
    <label for="name" class="text-sm">Title</label>
    <%= form.text_field :title, class: "rounded border-gray-200", id: "title", placeholder: "Course title" %>
  </div>

  <div class=" flex flex-col mt-4">
    <label for="name" class="text-sm">Description</label>
    <%= form.rich_text_area :description, class: "rounded border-gray-200", id: "description", placeholder: "Course description" %>
  </div>

  <div class=" flex flex-col mt-4">
    <label for="name" class="text-sm">Stripe price id</label>
    <%= form.text_field :stripe_price_id, class: "rounded border-gray-200", id: "title" %>
  </div>

  <div class=" flex flex-col mt-4">
    
    <%= admin_course.image.present? ? (image_tag admin_course.image, class: "w-64 rounded mb-2") : nil %>
    <label for="name" class="text-sm">Cover Image</label>
    <%= form.file_field :image, id: "image" %>
  </div>

  <div class=" flex flex-col mt-4">
    <label for="name" class="text-sm">Paid: </label>
    <%= form.check_box :paid, id: "paid" , class: "rounded border-gray-200"%>
  </div>

  <div class=" flex flex-col mt-4">
    <label for="name" class="text-sm">Premium Description</label>
    <%= form.rich_text_area :premium_description, class: "rounded border-gray-200", id: "premium_description", placeholder: "Premium Course description" %>
  </div>
  <div class="mt-4">
    <%= form.submit "Submit", class: "bg-amaranth-500 hover:bg-amaranth-700 rounded text-white-50 cursor-pointer px-4 py-2" %>
  </div>
<% end %>

app/views/admin/courses/edit.html.erb
<div class=" w-full flex flex-col justify-center items-center">
  <% content_for :title, "Editing course" %>



  <%= render "form", admin_course: @admin_course %>

  <br>

  <div>
    <%= link_to "Show this course", [:admin,@admin_course] %> |
    <%= link_to "Back to courses", admin_courses_path %>
  </div>
</div>

app/views/admin/courses/index.html.erb
<div class="w-full">
  <div class = "flex justify-end items-center">
    <%= link_to "New course", new_admin_course_path, class: "bg-amaranth-500 hover:bg-amaranth-700 px-4 py-2 cursor-pointer rounded text-white-50" %>
  </div>

    <p style="color: green"><%= notice %></p>

    <% content_for :title, "Courses" %>

    <h1>Courses</h1>

    <div id="admin_courses" class = "min-w-full flex flex-wrap justify-center gap-5 mt-6 pt-6">
      <% @admin_courses.each do |admin_course| %>
        <%= render admin_course %>
      <% end %>
    </div>

  
</div>

app/views/admin/courses/new.html.erb
<div class=" flex flex-col justify-start items-center w-full">
  <%= render "form", admin_course: @admin_course %>

  <br>

  <div>
    <%= link_to "Back to courses", admin_courses_path %>
  </div>
</div>

app/views/admin/courses/show.html.erb
<div class=" flex flex-col w-full items-center justify-start">
  <p style="color: green"><%= notice %></p>

  <%= render @admin_course %>

  <div class=" mt-4 flex gap-4">
    <%= link_to "Back to courses", admin_courses_path %>

    <%= button_to "Destroy this course", [:admin,@admin_course], method: :delete, 
      data: {'turbo-confirm': "Are you sure?" }    
    %>
  </div>
</div>